### ISSUE TITLE
Doesn't Install 

### ISSUE THREAD

**Issue by siddhant-curious** [haskell-beam/beam#444]
I've been trying to install and get beam working for past 2 days. 

Initially `beam-core` had issues with `resolver: lts-15.3` and I reverted back to `resolver: lts-14.27` after referring to: https://www.stackage.org/package/beam-core

I added latest commit as the documentation states 

```
extra-deps:
  - git: https://github.com/tathougies/beam.git
    commit: ff6d16daa189355db4cf24e90d8173768c1418bb
    subdirs:
      - beam-core
      - beam-sqlite
      - beam-postgres
```
and also added dependencies in `build-depends` of .cabal file. 

While I no longer have issues with beam-core dependencies, I get the following error when executing `stack build`. How do I resolve this? 

```
/Users/username/Documents/beam-learn/src/Lib.hs:5:1: error:
    Could not load module ‘Database.Beam’
    It is a member of the hidden package ‘beam-core-0.8.0.0’.
    Perhaps you need to add ‘beam-core’ to the build-depends in your .cabal file.
    Use -v to see a list of the files searched for.
  |
5 | import Database.Beam
  | ^^^^^^^^^^^^^^^^^^^^

/Users/username/Documents/beam-learn/src/Lib.hs:6:1: error:
    Could not load module ‘Database.Beam.Sqlite’
    It is a member of the hidden package ‘beam-sqlite-0.4.0.0’.
    Perhaps you need to add ‘beam-sqlite’ to the build-depends in your .cabal file.
    Use -v to see a list of the files searched for.
  |
6 | import Database.Beam.Sqlite
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
